require 'plugins.nvim-web-devicons'
require 'plugins.nvim-treesitter'
require 'plugins.nvim-autopairs'
require 'plugins.nvim-tree'
require 'plugins.toggleterm'
require 'plugins.telescope'

require 'plugins.lualine-nvim'
require 'plugins.comment'
require 'plugins.null-ls'
